### ISSUE TITLE
New icon for Party Manager 'Select Party' button

### ISSUE THREAD

**Issue by samcorcoran** [tsiemens/pathfinder-toolkit#40]
Currently the 'three faces' icon is being used. It is used elsewhere for other things, so perhaps a different icon representing parties is needed?

**Comment by tsiemens** [comment]
Since a party is already represented by a plural of objects, creating an icon to represent multiple parties is obviously a challenge. The best option might be to create a new icon for 'multiple characters' or 'select character'. In this case, those buttons would have two people in the icon, where as the icon for parties would have 3. See example here http://www.socialtosales.com/wp-content/uploads/2013/09/Group-Search.png (People icon vs groups icon)

**Comment by tsiemens** [comment]
Fixed. Changed icons for selecting characters to be just 2 people, and chosing parties is 3 people. This seems to be in line with other social media icon sets.
